### ISSUE TITLE
Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by antonkulaga** [neudinger/pyDockRMSD#3]
I am using pyDockRMSD to compute RMSD for DeepAb folding predictions against known pdbs. I clean the models and do pdb->pdbqt -> mol2 conversions, however, I constantly get segmentation faults.
I attach the models example
[inputs_and_conversions.zip](https://github.com/neudinger/pyDockRMSD/files/8079701/inputs_and_conversions.zip)
s

**Comment by neudinger** [comment]
The problem seems to came from memory allocation.
I used alloca to be able to alocate memory on the stack as the original c code.
The advantage is the memory is freed when the call stack is unqueue.
But alocate memory on the stack are very limited in size, that why normaly people used malloc but we need to released the memory by hand.

So i will change all allocations from the stack to the heap.
But i need to identify where i need to free.
If we don't free segmentation faults will still happening

I am on it but it will take time.

**Comment by neudinger** [comment]
@antonkulaga 
Can i add your files in the repository ?
I want want want to use them in regression test and integration test.
Thanks

However after fix the library:

Between 1ADQ_FV_deep.mol2 and 1adq_fixed_RF_short.mol2

I have this return:
"Template and query don't have the same bonding network."

Maybe i should test on other big file ?

**Comment by neudinger** [comment]
With no response i close this issue.

You can find last release here <https://github.com/neudinger/pyDockRMSD/releases/tag/pv1.0.0>
and here <https://pypi.org/project/pydockrmsd/>
